language: generic
sudo required

services:
  -docker

before_install:
  - docker build -t 17252/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true 17252/react-test npm test

after_success:
  - docker build -t 17252/multi-client ./client
  - docker build -t 17252/multi-nginx ./nginx
  - docker build -t 17252/multi-server ./server
  - docker build -t 17252/multi-workder ./workder
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 17252/multi-client
  - docker push 17252/multi-nginx 
  - docker push 17252/multi-server
  - docker push 17252/multi-workder


